# This workflow is used to update the platform SDK dependency when new version of the SDK is published to the npm registry.
# It creates a pull request with the updated dependencies for both example apps.
name: SDK Package Update Action

on:
  workflow_dispatch:

env:
  PACKAGE_NAME: "@microblink/platform-sdk"
  PACKAGE_VERSION: ""

jobs:
  update-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Update to the latest version of the SDK
        run: |
          echo "Updating React example..."
          pnpm --prefix example-react add ${{ env.PACKAGE_NAME }}@latest
          
          echo "Updating Vanilla example..."
          pnpm --prefix example-vanila add ${{ env.PACKAGE_NAME }}@latest

      - name: Build example apps
        run: |
          echo "Building React example..."
          pnpm --prefix example-react build
          
          echo "Building Vanilla example..."
          pnpm --prefix example-vanila build 
      
      - name: Get the latest version
        run: |
          echo "PACKAGE_VERSION=$(pnpm show ${{ env.PACKAGE_NAME }} version)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pr@v6
        with:
          commit-message: "chore: update ${{ env.PACKAGE_NAME }} to latest version"
          title: "Update ${{ env.PACKAGE_NAME }} to ${{ env.PACKAGE_VERSION }}"
          body: |
            This PR updates the ${{ env.PACKAGE_NAME }} dependency to version ${{ env.PACKAGE_VERSION }} for both example apps.
            The changes are automatically generated by the SDK Package Update Action.
            Please review the changes and merge the PR if everything looks good.
          branch: "chore/update-${{ env.PACKAGE_NAME }}"
          delete-branch: true
