# This workflow is used to update the platform SDK dependency when new version of the SDK is published to the npm registry.
# It creates a pull request with the updated dependencies for both example apps.
name: SDK Package Update Action

on:
  workflow_dispatch:

env:
  PACKAGE_NAME: "@microblink/platform-sdk"
  PACKAGE_VERSION: ""

jobs:
  update-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Update example-react to the latest version of the SDK
        run: |
          cd example-react
          echo "Installing dependencies..."
          npm ci
          
          echo "Updating package..."
          npm install ${{ env.PACKAGE_NAME }}@latest
          
          echo "Building..."
          npm run build
          
      - name: Update example-vanilla to the latest version of the SDK
        run: |
          cd example-vanilla
          echo "Installing dependencies..."
          npm ci 
          
          echo "Updating package..."
          npm install ${{ env.PACKAGE_NAME }}@latest
          
          echo "Building..."
          npm run build

      - name: Get the latest version
        run: |
          echo "PACKAGE_VERSION=$(npm show ${{ env.PACKAGE_NAME }} version)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pr@v6
        with:
          commit-message: "chore: update ${{ env.PACKAGE_NAME }} to latest version"
          title: "Update ${{ env.PACKAGE_NAME }} to ${{ env.PACKAGE_VERSION }}"
          body: |
            This PR updates the ${{ env.PACKAGE_NAME }} dependency to version ${{ env.PACKAGE_VERSION }} for both example apps.
            The changes are automatically generated by the SDK Package Update Action.
            Please review the changes and merge the PR if everything looks good.
          branch: "chore/update-${{ env.PACKAGE_NAME }}"
          delete-branch: true
